Topics Functionality  (Frontend & Backend)
Unirep/Unirep-Social pull request #195
Opened 2022-12-26 17:13 UTC by AnthonyMadia

< Creating this PR on a separate branch to avoid confusion and make it easier to receive comments considering previous topics PR was reverted >

**_Please note the `core` schema of the `Post` has been changed to include a `topic` field which will require the docker image to be rebuilt _**

This PR contains the core functionality of adding topics to Unirep Social.

Essentially, the `topics` are taken from the page the user navigates to. For example, if a user navigates to the `localhost:3000/technology` page, the code will get the `technology` topic from URL and push that state to the `new` page. On submit, the `topic` will be attached to the post being sent to the backend. Then, posts are queried by topic when the user visits `localhost:3000/technology` in a similar fashion; by taking the topic from the URL and using it to query topics from the backend based on new, boost, comments, etc.

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`yarn build`) was run locally and any changes were pushed
- [ ] Lint (`yarn lint --check`) has passed locally and any fixes were made for failures

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: #167 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2022-12-26 21:02 UTC, kittybest commented
@AnthonyMadia  for the frontend part, I make a PR base on your PR, that's just a try to show my opinion, not force to merge.
https://github.com/Unirep/Unirep-Social/pull/196
If you agree that's better, please merge that to this branch before you merge this to **main**
(because last time when I make a PR to your branch, you approve it but merge your PR to **main** before merge mine to your branch >< just remind)

2022-12-28 03:10 UTC, vivianjeng requested changes

2022-12-28 16:35 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
This works and makes a lot more sense, but I still have problems with getting the `query` to work as intended. I can log out the `query` in the backend but the UI is still not updating the posts correctly. This makes me think it's a frontend issue but not entirely sure.

2022-12-28 16:35 UTC, AnthonyMadia commented on packages/frontend/cypress/e2e/signup.cy.ts
> +    it.skip('ensures that user can submit a post', () => {
yes this can be fixed before merging

2022-12-28 16:46 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
Going to figure out how to condense the `loadFeed` functionality in the `Post` context using `topics` as an optional parameter. I think this should fix it.

2022-12-28 20:01 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
I condensed the backend logic and `loadFeed` functionality in the `Post` context and have the topic page queries working, but now I have problems with having the `general` posts render in the frontend. I believe this has something to do with how the `keys` are being handled on the `MainPage` component and within the `Post` context. 

Would be helpful to have more eyes to understand what I am doing wrong. @kittybest @vivianjeng

2022-12-29 17:03 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
Just fixed this -- I was handling the `postIds` incorrectly on the `MainPage`. 

Had to change this:

```ts
const getPostIds = () => {
        if (typeof topic === 'undefined') {
            return postContext.feeds[query] || []
        }
        return postContext.feeds[`${query}-${topic}`] || []
    } 
```

to:

```ts
const getPostIds = () => {
        const key = `${query}-${topic || 'general'}`
        return postContext.feeds[key] || []
    }
```

That was very annoying lol.

2022-12-30 03:22 UTC, vivianjeng commented
so what do you expect the topic `general` to do?
Is it the posts with all kind of topics (technology, philosophy,...and so on) or the posts with no topics (should not include the posts with topics)

2022-12-30 10:38 UTC, AnthonyMadia commented
Doris mentioned that she thinks it should be all the posts which I think is a good idea. Right now it is just posts without a specific topic, but I can change that. @vivianjeng

2022-12-30 18:04 UTC, AnthonyMadia commented
My only concern with the `loadPosts` function in the backend is if it if extra logic is needed to handle loading posts created _without_ a topic field. What are your thoughts on this? @vivianjeng

2023-01-04 16:06 UTC, kittybest commented
@AnthonyMadia  I think let's just keep the `TopicMenu` :)
But several things to change:
1. leave it only on `mainPage` instead of everywhere
2. maybe remove the **new post** button on the top nav bar
3. **General** topic might be posts without specific topics? while **All** topic might be *all* posts, how do you think?
4. Add the dropdown menu for choosing topic while creating posts, can refer to my PR for how to make it. (Chance just mentioned)
5. Modify `TopicMenu` while the screen becomes smaller, and while in mobile size, it becomes a dropdown menu (Chiali just mentioned)
6. according to *4*, I think we can change the route `/{topic}/new` back to just `/new`, how do u think?
7. according to *3*, add **General** and **All** on the menu, but it might look kind of crowded?
8. add background-color on the menu choice if it is chosen.

to answer your question of `loadPosts`, there's no problem with it if you just leave the `topic` blank(undefined).

another things to mention:
1. I find out that you remove the **[query]-user** in `feedKey`, I think we should bring it back :)
2. For the code part, I'll check it after the above changes are done

2023-01-05 17:07 UTC, kittybest commented
https://user-images.githubusercontent.com/9023842/210837722-98ca3ab8-5409-447e-912a-62e7f192a4c9.mov
1. The **General** topic should be different from **All**, else it's confusing that `/` and `/general` are the same.

https://user-images.githubusercontent.com/9023842/210838463-dd9e2a1d-1323-4dd8-97d9-281ce75a400e.mov
2. Maybe the collapse range should smaller than 1200px? I think now it's around 1076px

![image](https://user-images.githubusercontent.com/9023842/210838874-bf2e21b4-ff9d-40d2-8e89-2bbaeaa22f63.png)
3. I think we also don't need the topics above while creating post

2023-01-05 17:11 UTC, AnthonyMadia commented
Commits should reflect all of the feedback on your comment and mentioned in yesterday's meeting. 

Still a few  things to consider:

1. I added the 'General' topic to the TopicMenu, but the `/` route still renders what the 'General' topic page renders. Should we just redirect the `/` route to the 'General' page?

> I find out that you remove the [query]-user in `feedKey`, I think we should bring it back :)

2. I am not sure what this means. Can you clarify where you want the change and the purpose of this?

> General topic might be posts without specific topics? while All topic might be all posts, how do you think?

3. Currently, the 'General' page includes _all_ the posts so not sure there would be a need to create an 'All' page.

> 3. I think we also don't need the topics above while creating post

4. Makes sense. I also want to add support that if a user clicks 'create post' on a certain topics page, that topic would automatically be selected when they arrive at the new page.

2023-01-06 17:13 UTC, kittybest commented
> I added the 'General' topic to the TopicMenu, but the / route still renders what the 'General' topic page renders. Should we just redirect the / route to the 'General' page?
> Currently, the 'General' page includes all the posts so not sure there would be a need to create an 'All' page.

So I think we should have both **General** and **All** page? while the `/` route will render all posts, and the `/general` just render the posts without topics.

> I am not sure what this means. Can you clarify where you want the change and the purpose of this?

We originally used it on **UserPage**, I think. If you look back in the `userPage.tsx` file in *main* branch, the `feedKey` will have an argument called `epks: string[] = []`, and if `epks.length > 0`, the `feedKey` will return **[query]-user**. Actually I think **-user** is something similar to **-[topic]**, so I think we should keep the **-user** to let the user quickly get their posts on **UserPage**. Now I don't think the user can get their own posts on **UserPage**. 
You can refer to my branch `topic-doris`, go to `Post.ts` and `userPage.tsx` to get more details.

> There are also some weird state issues I'm dealing with between the 'General' and / route. They are doing the same queries to the backend, but not updating as expected in the frontend.

They won't do the same query to backend :) 
Actually, if you want to get **ALL** posts, you must send `topic: undefined`; however, if you want to get **GENERAL** posts which might be those without specific topics, you must send `topic: ''` to the backend. 
You can refer to my branch `topic-doris`, go to `PostRouter.ts` and `Post.ts` to get more details.

2023-01-10 20:02 UTC, kittybest commented
<img width="818" alt="image" src="https://user-images.githubusercontent.com/9023842/211650005-5bf46a4a-ef85-4b84-b3cf-db044f4a0043.png">
If you didn't add `[query]-user` in `feedKey`, this will happen----I can see the posts which is not mine (the above one is post by another account).

Originally the *None* option is just for general type of post, but now since we have the choice *general*, we can just set the default to *general* in dropdown menu :)

I think even **All** post page should let the user to post, else someone like me won't find where to publish a new post and feeling unwilling to use this website. While the use click post on **All** page (`/`), just set the topic to default one, no matter it is *general* or *''*.

@AnthonyMadia

2023-01-10 21:38 UTC, AnthonyMadia commented
Ah okay, that makes sense. Just made the changes @kittybest. 

I _think_ this is good to merge but going to double check code.

2023-01-11 19:34 UTC, AnthonyMadia commented
Great catch. I was not setting the topic state correctly within the `writingField` component when user navigates to the new page from the All page. This commit should fix the problem.

2023-01-12 18:26 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
So this is to make it obvious that when the if statement is truthy, it will grab _all_ the posts for the `All` page.

2023-01-12 18:28 UTC, AnthonyMadia commented on packages/frontend/src/pages/mainPage/mainPage.tsx
> +        postContext.loadFeed(query, topic, postContext.feeds[key] || [])
The posts in general have a topic now. Their topic is `general`.

2023-01-12 18:40 UTC, kittybest commented on packages/frontend/src/pages/mainPage/mainPage.tsx
> +        postContext.loadFeed(query, topic, postContext.feeds[key] || [])
yes, this is an old review hahahaha

2023-01-12 18:41 UTC, kittybest commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
but actually they are doing the same thing, i don't think you should split them, just add comment to tell others.

2023-01-12 18:50 UTC, AnthonyMadia commented on packages/backend/src/routes/PostRouter.ts
> +        res.json(posts.slice(0, Math.min(LOAD_POST_COUNT, posts.length)))
Right. Yea, idk why I was overthinking this logic. I eliminated the `else` statement and changed the `if` statement to `if (req.query.topic === undefined || req.query.topic) {` which I believe works. Pushing now.

2023-01-12 19:03 UTC, kittybest commented on packages/backend/src/routes/PostRouter.ts
> +    if (req.query.topic === undefined || req.query.topic) {
This is redundant, since it will always return true, `req.query.topic` is either `undefined` or has value

2023-01-12 19:06 UTC, kittybest approved these changes

2023-01-13 15:36 UTC, vivianjeng commented
It fails when commenting, because there is no `topic` detected.
and the error message is like this.

<img width="573" alt="" src="https://user-images.githubusercontent.com/17507085/212358217-5f5377f3-d15e-4c00-a5aa-098b783d5fed.png">

<img width="573" alt="" src="https://user-images.githubusercontent.com/17507085/212358224-e34a764a-ca40-49db-90bf-829ee29005d0.png">

2023-01-13 15:49 UTC, vivianjeng requested changes
I found that I cannot **comment**
like this: https://github.com/Unirep/Unirep-Social/pull/195#issuecomment-1382027334
and I cannot **edit post** and the error message shows the same
please try to get `topic` in these two situations.
or if it doesn't require `topic` as input, then use like `topic?.toLowerCase()` to make it `undefined`.

2023-01-13 15:49 UTC, vivianjeng commented on packages/backend/src/routes/PostRouter.ts
> +    console.log(topic)
debug message can be removed

2023-01-13 15:49 UTC, vivianjeng commented on packages/frontend/cypress/e2e/signup.cy.ts
> +    it.skip('ensures that user can submit a post', () => {
this can be fixed?

2023-01-13 16:05 UTC, AnthonyMadia commented
>  then use like topic?.toLowerCase() to make it undefined. 

This seemed to have fixed the comment problem. 

E2e test is also fixed.

2023-01-13 16:16 UTC, vivianjeng approved these changes
LGTM
When the CI passes, it can be merged 👍🏻

2023-01-13 16:19 UTC, merged